#!/usr/bin/env yaml-to-dockerfile

- from: ubuntu:20.04

- run:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y
      build-essential
      nodejs
      npm

- run:
  - mkdir /node_modules
  - cd /
  - npm install -g coffeescript
  - npm install
      domino
      ingy-prelude
      turndown
      turndown-plugin-gfm
      smartwrap

- copy: [ html-to-markdown, /bin ]

# - !import ../common/dev-tools.yaml
- run:
    apt-get install -y
      git
      silversearcher-ag
      tig
      tmux
      vim
